In [1]:
import torch

In [2]:
print("support CUDA?:", torch.cuda.is_available())

support CUDA?: True


In [3]:
x = torch.tensor([10.0])
x = x.cuda()
print(x)

tensor([10.], device='cuda:0')


In [4]:
y = torch.randn(2, 3)
y = y.cuda()
print(y)

tensor([[-0.8987, -1.3874,  0.5406],
        [-0.9407,  0.3206, -0.5501]], device='cuda:0')


In [5]:
z = x + y
print(z)

tensor([[ 9.1013,  8.6126, 10.5406],
        [ 9.0593, 10.3206,  9.4499]], device='cuda:0')


In [6]:
from torch.backends import cudnn
print("support cudnn?:", cudnn.is_acceptable(x))

support cudnn?: True


In [7]:
torch.randn?