In [1]:
import torch
from torch import nn
from torch.nn import functional as F

存数组

In [2]:
x = torch.arange(4)
torch.save(x, 'save/x-file')

In [3]:
x2 = torch.load('save/x-file')
x2

tensor([0, 1, 2, 3])

存张量

In [4]:
y = torch.zeros(4)
torch.save([x, y], 'save/x-files')
x2, y2 = torch.load('save/x-files')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

存字典

In [5]:
mydict  = {'x': x, 'y': y}
torch.save(mydict, 'save/mydict')
mydict2 = torch.load('save/mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

#### 加载和保存模型参数

In [6]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)
    def forward(self, x):
        return self.output(F.relu(self.hidden(X)))

In [7]:
net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

In [8]:
# 存所有参数
torch.save(net.state_dict(), 'save/mlp.params')

In [9]:
# 取文件中的参数，先建立新模型（参数被初始化），然后用老数据overwrite新模型的参数
clone = MLP()
clone.load_state_dict(torch.load('save/mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [10]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])