In [2]:
import torch

In [3]:
print("support CUDA?:", torch.cuda.is_available())

support CUDA?: True


In [4]:
torch.cuda.device_count()

1

In [5]:
torch.cuda.get_device_name(0)

'GeForce GTX 1660 SUPER'

In [6]:
x = torch.tensor([10.0])
x = x.cuda()
print(x)

tensor([10.], device='cuda:0')


In [7]:
y = torch.randn(2, 3)
y = y.cuda()
print(y)

tensor([[ 0.7613,  0.3424, -0.9773],
        [ 0.5315,  0.7848,  0.4192]], device='cuda:0')


In [8]:
z = x + y
print(z)

tensor([[10.7613, 10.3424,  9.0227],
        [10.5315, 10.7848, 10.4192]], device='cuda:0')


In [9]:
from torch.backends import cudnn
print("support cudnn?:", cudnn.is_acceptable(x))

support cudnn?: True
